insert into identidadgeneros (descripcion, estado) values
('MUJER', 1),
('HOMBRE', 1),
('MUJER TRANSGENERO', 1),
('HOMBRE TRANSGENERO', 1);

select * from identidadgeneros;

INSERT INTO etnias (descripcion, estado) VALUES
('NINGUNA', '1'),
('KOGI', '1'),
('WAYUU', '1'),
('ARHUACO', '1'),
('EMBERA', '1'),
('GUAMBIANOS', '1'),
('PASTOS', '1'),
('MUISCAS', '1'),
('HUITOTO', '1'),
('TICUNA', '1'),
('NUKAK MAKU', '1'),
('KAMSA', '1'),
('SANHA', '1'),
('CHIMILA', '1'),
('MOCANA', '1'),
('ZENÃº', '1'),
('TULE', '1'),
('WAUNAAN', '1'),
('COCONUCO', '1'),
('YANACONA', '1'),
('PAEZ', '1'),
('AWA', '1'),
('DUJO', '1'),
('PIAPOCO', '1'),
('PIJAO', '1'),
('GUAYABERO', '1'),
('ACHAGUA', '1'),
('TUNEBO', '1'),
('CHITAREROS', '1'),
('GUANE', '1'),
('YAGUA', '1'),
('COCAMA', '1'),
('CHIRICO', '1'),
('PUINAVE', '1'),
('SIKUANI', '1'),
('MAKAGUAJE', '1'),
('MUINANE', '1'),
('CUIABA', '1');

select * from etnias;


INSERT INTO poblacional (descripcion, estado) VALUES
(' NINGUNO', 1),
('NIÑO', 0),
('NIÑA', 0),
('ADOLESCENTE', 1),
('INDIGENA O ETNIAS', 1),
('DEFENSOR DE DDHH', 0),
('INTEGRANTES MESAS DE VICTIMAS', 0),
('Funcionario pÃºblico', 0),
('Servidor pÃºblico', 0),
('Fuerza pÃºblica', 0),
('VÃ­ctima conflicto enf. dife', 0),
('ADULTO MAYOR', 1),
('Persona con capacidad diversa', 0),
('Enfermo catastrÃ³fico', 0),
('Habitante de calle', 0),
('Sindicalista', 0),
('Educadores', 0),
('Bisexual', 0),
('Gay', 0),
('Itersexual', 0),
('Lesbianas', 0),
('TransgÃ©nero', 0),
('Travestis', 0),
('LGTBI', 1),
('AFRODESCENDIENTES', 1);